#include <memory.h>
#include <stdio.h>

int main(void)
{
     int i = 0;
     unsigned char arr[30000];
     memset(arr, 0, sizeof(arr));
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     while(arr[i])
     {
          i++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          i--;
          arr[i]--;
     }
     i++;
     while(arr[i])
     {
          i--;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          i++;
          arr[i]--;
     }
     arr[i]++;
     i--;
     while(arr[i])
     {
          i++;
          arr[i]--;
          i--;
          while(arr[i])
          {
               i++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               i--;
               arr[i]--;
          }
          i++;
          while(arr[i])
          {
               i--;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               i++;
               arr[i]--;
          }
          i--;
          while(arr[i])
          {
               i++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               i--;
               arr[i]--;
          }
          arr[i]++;
          i++;
          while(arr[i])
          {
               i++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               while(arr[i])
               {
                    i++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    i--;
                    arr[i]--;
               }
               i++;
               arr[i]++;
               putchar(arr[i]);
               arr[i]--;
               putchar(arr[i]);
               while(arr[i])
               {
                    arr[i]--;
               }
               i--;
               i--;
               while(arr[i])
               {
                    arr[i]--;
               }
               i--;
               arr[i]--;
               i++;
          }
          i--;
          while(arr[i])
          {
               i++;
               i++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               while(arr[i])
               {
                    i++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    arr[i]++;
                    i--;
                    arr[i]--;
               }
               i++;
               putchar(arr[i]);
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               putchar(arr[i]);
               while(arr[i])
               {
                    arr[i]--;
               }
               i--;
               i--;
               i--;
               arr[i]--;
          }
     }
     i++;
     while(arr[i])
     {
          i++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          while(arr[i])
          {
               i++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               arr[i]++;
               i--;
               arr[i]--;
          }
          i++;
          putchar(arr[i]);
          while(arr[i])
          {
               arr[i]--;
          }
          i--;
          i--;
          arr[i]--;
     }
     i--;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     while(arr[i])
     {
          i++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          i++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          i++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          arr[i]++;
          i++;
          arr[i]++;
          i--;
          i--;
          i--;
          i--;
          arr[i]--;
     }
     i++;
     arr[i]--;
     putchar(arr[i]);
     i++;
     arr[i]--;
     putchar(arr[i]);
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     putchar(arr[i]);
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     putchar(arr[i]);
     i--;
     putchar(arr[i]);
     i++;
     i++;
     putchar(arr[i]);
     arr[i]++;
     arr[i]++;
     putchar(arr[i]);
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     arr[i]++;
     putchar(arr[i]);
     putchar(arr[i]);
     i--;
     arr[i]--;
     putchar(arr[i]);
     i++;
     i++;
     arr[i]--;
     putchar(arr[i]);
     while(arr[i])
     {
          while(arr[i])
          {
               arr[i]--;
          }
          i--;
     }
     return 0;
}
